/* ============================================================
   ZAMAN — Product Catalog
   All product photography sourced from Pexels (free license,
   no attribution required). See README.md for source list.
   ============================================================ */

const PEXELS = (id, w = 900) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}`;

const ZAMAN_PRODUCTS = [
  {
    id: 1,
    name: "ZAMAN Classic",
    category: "Classic",
    price: 4999,
    oldPrice: null,
    description:
      "A refined everyday timepiece built on clean lines and an unhurried dial layout — the watch that started the ZAMAN line.",
    image: PEXELS(1467188),
    images: [PEXELS(1467188), PEXELS(5058216), PEXELS(3419331)],
    rating: 4.8,
    reviews: 132,
    movement: "Quartz",
    caseMaterial: "Stainless Steel",
    glass: "Mineral Crystal",
    strap: "Italian Leather",
    waterResistance: "5 ATM",
    caseDiameter: "40mm",
  },
  {
    id: 2,
    name: "ZAMAN Noir",
    category: "Noir",
    price: 6499,
    oldPrice: null,
    description:
      "All black, all intent. A matte PVD case and a sunburst dial give Noir a presence that reads from across the room.",
    image: PEXELS(16739804),
    images: [PEXELS(16739804), PEXELS(2494608), PEXELS(1697218)],
    rating: 4.9,
    reviews: 208,
    movement: "Automatic",
    caseMaterial: "Black PVD Stainless Steel",
    glass: "Sapphire Crystal",
    strap: "Black Leather",
    waterResistance: "10 ATM",
    caseDiameter: "42mm",
  },
  {
    id: 3,
    name: "ZAMAN Aurelius",
    category: "Signature",
    price: 7999,
    oldPrice: null,
    description:
      "Named for the philosopher-emperor. Aurelius pairs a polished gold-tone case with a guilloché dial for occasions that call for weight.",
    image: PEXELS(3809175),
    images: [PEXELS(3809175), PEXELS(28135838), PEXELS(31642726)],
    rating: 4.9,
    reviews: 96,
    movement: "Automatic",
    caseMaterial: "Gold-Tone Stainless Steel",
    glass: "Sapphire Crystal",
    strap: "Stainless Steel Bracelet",
    waterResistance: "5 ATM",
    caseDiameter: "41mm",
  },
  {
    id: 4,
    name: "ZAMAN Chrono",
    category: "Chronograph",
    price: 9499,
    oldPrice: null,
    description:
      "Three sub-dials, one purpose: precision under pressure. Chrono is built for people who track their time closely.",
    image: PEXELS(190819),
    images: [PEXELS(190819), PEXELS(9267840), PEXELS(10688098)],
    rating: 4.7,
    reviews: 74,
    movement: "Chronograph Quartz",
    caseMaterial: "Stainless Steel",
    glass: "Sapphire Crystal",
    strap: "Stainless Steel Bracelet",
    waterResistance: "10 ATM",
    caseDiameter: "43mm",
  },
  {
    id: 5,
    name: "ZAMAN Meridian",
    category: "Classic",
    price: 5499,
    oldPrice: null,
    description:
      "A slimmer case and a warmer gold bezel make Meridian the most understated piece in the Classic line.",
    image: PEXELS(3419331),
    images: [PEXELS(3419331), PEXELS(1467188), PEXELS(37050003)],
    rating: 4.6,
    reviews: 58,
    movement: "Quartz",
    caseMaterial: "Gold-Tone Stainless Steel",
    glass: "Mineral Crystal",
    strap: "Brown Leather",
    waterResistance: "3 ATM",
    caseDiameter: "38mm",
  },
  {
    id: 6,
    name: "ZAMAN Obsidian",
    category: "Noir",
    price: 6999,
    oldPrice: null,
    description:
      "Named for volcanic glass. Obsidian's deep-black dial and leather strap disappear into a tuxedo cuff without trying.",
    image: PEXELS(2494608),
    images: [PEXELS(2494608), PEXELS(16739804), PEXELS(60147)],
    rating: 4.8,
    reviews: 121,
    movement: "Automatic",
    caseMaterial: "Black PVD Stainless Steel",
    glass: "Sapphire Crystal",
    strap: "Black Leather",
    waterResistance: "5 ATM",
    caseDiameter: "41mm",
  },
  {
    id: 7,
    name: "ZAMAN Imperial",
    category: "Signature",
    price: 12999,
    oldPrice: 14999,
    description:
      "The flagship. A fully gold-toned case, domed sapphire crystal, and a dial finished by hand — Imperial is ZAMAN at its highest expression.",
    image: PEXELS(28135838),
    images: [PEXELS(28135838), PEXELS(3809175), PEXELS(380782)],
    rating: 5.0,
    reviews: 41,
    movement: "Automatic",
    caseMaterial: "18K Gold-Plated Steel",
    glass: "Domed Sapphire Crystal",
    strap: "Stainless Steel Bracelet",
    waterResistance: "5 ATM",
    caseDiameter: "42mm",
  },
  {
    id: 8,
    name: "ZAMAN Voyager",
    category: "Chronograph",
    price: 8499,
    oldPrice: null,
    description:
      "Built for movement. A tachymeter bezel and a legible dial make Voyager equally at home on a runway or a runway show.",
    image: PEXELS(1697218),
    images: [PEXELS(1697218), PEXELS(190819), PEXELS(16739804)],
    rating: 4.7,
    reviews: 63,
    movement: "Chronograph Quartz",
    caseMaterial: "Stainless Steel",
    glass: "Mineral Crystal",
    strap: "Black Leather",
    waterResistance: "10 ATM",
    caseDiameter: "44mm",
  },
  {
    id: 9,
    name: "ZAMAN Heritage",
    category: "Classic",
    price: 5999,
    oldPrice: 6999,
    description:
      "A vintage-inspired case shape and a warm, aged dial finish nod to the watches that made this category timeless.",
    image: PEXELS(60147),
    images: [PEXELS(60147), PEXELS(5058216), PEXELS(1467188)],
    rating: 4.7,
    reviews: 87,
    movement: "Automatic",
    caseMaterial: "Stainless Steel",
    glass: "Mineral Crystal",
    strap: "Brown Leather",
    waterResistance: "3 ATM",
    caseDiameter: "39mm",
  },
  {
    id: 10,
    name: "ZAMAN Eclipse",
    category: "Noir",
    price: 7499,
    oldPrice: null,
    description:
      "A brushed steel case with a near-black dial — Eclipse sits between Noir's boldness and Classic's restraint.",
    image: PEXELS(33511755),
    images: [PEXELS(33511755), PEXELS(2494608), PEXELS(190819)],
    rating: 4.6,
    reviews: 45,
    movement: "Quartz",
    caseMaterial: "Stainless Steel",
    glass: "Sapphire Crystal",
    strap: "Stainless Steel Bracelet",
    waterResistance: "10 ATM",
    caseDiameter: "40mm",
  },
  {
    id: 11,
    name: "ZAMAN Regal",
    category: "Signature",
    price: 10499,
    oldPrice: null,
    description:
      "A cool-toned case and a deep blue-black dial give Regal a formality the rest of the Signature line only hints at.",
    image: PEXELS(27531462),
    images: [PEXELS(27531462), PEXELS(3809175), PEXELS(31642726)],
    rating: 4.8,
    reviews: 52,
    movement: "Automatic",
    caseMaterial: "Stainless Steel",
    glass: "Domed Sapphire Crystal",
    strap: "Stainless Steel Bracelet",
    waterResistance: "5 ATM",
    caseDiameter: "41mm",
  },
  {
    id: 12,
    name: "ZAMAN Pulse",
    category: "Chronograph",
    price: 8999,
    oldPrice: null,
    description:
      "A lighter, sport-leaning chronograph with a two-tone dial for reading time at a glance, mid-stride.",
    image: PEXELS(10688098),
    images: [PEXELS(10688098), PEXELS(190819), PEXELS(9267840)],
    rating: 4.5,
    reviews: 39,
    movement: "Chronograph Quartz",
    caseMaterial: "Stainless Steel",
    glass: "Mineral Crystal",
    strap: "Brown Leather",
    waterResistance: "5 ATM",
    caseDiameter: "42mm",
  },
];

/* Utility lookups used across pages */
function getProductById(id) {
  return ZAMAN_PRODUCTS.find((p) => p.id === Number(id));
}

function formatEGP(amount) {
  return "EGP " + amount.toLocaleString("en-US");
}
